### PR TITLE
[MAIN] Update doctest to remove deprecation errors for Macs

### PR DESCRIPTION
**Pull request by adam2392**
Fixes: #15

### CODE REVIEW

**Comment by adam2392** [comment]
Hi @hameerabbasi just want to clarify, would it be helpful for me to go ahead and fix all the CI errors as well on this PR to grab them all at once? I'm starting to look thru the code to understand and map all the level format functions in the paper to where they should be implemented.

**Comment by hameerabbasi** [comment]
Yes, master should always be green. 😅

**Comment by hameerabbasi** [comment]
Ah, style fixes. The README goes into how to fix those. 😉

**Review by hameerabbasi — APPROVED** [review]
LGTM! Thanks, @adam2392!

**Pull request merged**
