### PR TITLE
[ENH] Adding Tensor implementation

### PR DESCRIPTION
**Pull request by adam2392**
Towards: #28 

~The only open questions that are remaining for the Tensor implementation If I understand correctly:~

~1. what should `get_data` look like? Variadic input of indices? and output a single element? Should it iterate over all the levels sequentially then?
2. how would we add elements to a tensor? Would it look like the following, where we iterate over the entire thing?~

This PR now implements a barebones Tensor class that wraps a tuple of levels and a data-vector and refactors certain methods of Coiterate to private.

There still needs to be compile-time checks for ensuring the Tensor is "even valid". Not sure how to best do that yet, but at a high-level things like: i) do all the levels line up? ii) will the data vector be accessed properly w/o segfault?

### CODE REVIEW

**Comment by adam2392** [comment]
> 1. what should `get_data` look like? Variadic input of indices? and output a single element? Should it iterate over all the levels sequentially then?
> 2. how would we add elements to a tensor? Would it look like the following, where we iterate over the entire thing?
> 
> ```
> for idx != i:
>         append(I, j, ithlevel)
>         for jdx <= j:
>             append(i,j,k, jthlevel)
>             for kdx <= k:
>                 append(value, kthlevel)
> ```

**Comment by adam2392** [comment]
Re implementing the iterator inside `Tensor`: Should this look at a high-level essentially like the design of coiteration with an iteration_helper and such? 

In some way we are "coiterating" over a collection of levels, but just in order rather than skipping some indices as in coiteration.

cc: @hameerabbasi @bharath2438

**Comment by hameerabbasi** [comment]
I think for a single tensor one doesn't need to co-iterate over levels at all, only over a single level for each dimension.

**Comment by adam2392** [comment]
> I think for a single tensor one doesn't need to co-iterate over levels at all, only over a single level for each dimension.

Say we have 3 stacked levels that define a sparse 3D tensor (s1, s2, s3). Then to iterate over these, we would need to define three iterators during the constructor of the Tensor iterator right? However, how would we define these to have the correct PKm1?

```
// for example: this is incorrect, since each iterator is starting at the beginning
auto it_helper1 = s1.iter_helper(std::make_tuple(), ZERO);
auto it_helper2 = s2.iter_helper(std::make_tuple(), ZERO);
auto it_helper3 = s3.iter_helper(std::make_tuple(), ZERO);

// it should look something like this?
auto it_helper1 = s1.iter_helper(std::make_tuple(), ZERO);
auto it_helper2 = s2.iter_helper(std::make_tuple(), it_helper1.begin());
auto it_helper3 = s3.iter_helper(std::make_tuple(), it_helper2.begin());
```

I think it would be useful to have a chat to clarify how the `iter_helper` design works in the different levels if I am misunderstanding

**Comment by hameerabbasi** [comment]
The tests for the levels already define how to iterate over a stack of levels.

**Comment by adam2392** [comment]
Okay @hameerabbasi this basic tensor implementation is good to go for now based on our disc., unless you have an idea for how to easily implement the compile-time check I describe in the PR description?

I simplified the datatype to be using the Data::value_type, which simplifies the template API for Tensor.

I figured, I can start working on the MergeLattice PR #27, and modify the Tensor implementation as needed at that point.

**Review by hameerabbasi — APPROVED** [review]

**Pull request merged**
